# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='flow_frame.proto',
  package='VideoFramework',
  serialized_pb='\n\x10\x66low_frame.proto\x12\x0eVideoFramework\"!\n\tFlowPoint\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\"7\n\x0b\x46lowMatches\x12(\n\x05point\x18\x01 \x03(\x0b\x32\x19.VideoFramework.FlowPoint\"9\n\tFlowFrame\x12,\n\x07matches\x18\x01 \x03(\x0b\x32\x1b.VideoFramework.FlowMatchesB\x02H\x01')




_FLOWPOINT = descriptor.Descriptor(
  name='FlowPoint',
  full_name='VideoFramework.FlowPoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='x', full_name='VideoFramework.FlowPoint.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='y', full_name='VideoFramework.FlowPoint.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=36,
  serialized_end=69,
)


_FLOWMATCHES = descriptor.Descriptor(
  name='FlowMatches',
  full_name='VideoFramework.FlowMatches',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='point', full_name='VideoFramework.FlowMatches.point', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=71,
  serialized_end=126,
)


_FLOWFRAME = descriptor.Descriptor(
  name='FlowFrame',
  full_name='VideoFramework.FlowFrame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='matches', full_name='VideoFramework.FlowFrame.matches', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=128,
  serialized_end=185,
)

_FLOWMATCHES.fields_by_name['point'].message_type = _FLOWPOINT
_FLOWFRAME.fields_by_name['matches'].message_type = _FLOWMATCHES
DESCRIPTOR.message_types_by_name['FlowPoint'] = _FLOWPOINT
DESCRIPTOR.message_types_by_name['FlowMatches'] = _FLOWMATCHES
DESCRIPTOR.message_types_by_name['FlowFrame'] = _FLOWFRAME

class FlowPoint(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FLOWPOINT
  
  # @@protoc_insertion_point(class_scope:VideoFramework.FlowPoint)

class FlowMatches(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FLOWMATCHES
  
  # @@protoc_insertion_point(class_scope:VideoFramework.FlowMatches)

class FlowFrame(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FLOWFRAME
  
  # @@protoc_insertion_point(class_scope:VideoFramework.FlowFrame)

# @@protoc_insertion_point(module_scope)
